spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mybatis
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  mybatis:
    mapper-locations: classpath:mappers/*.xml
    configuration:
      map-underscore-to-camel-case: true
