spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mybatis
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    dialect: org.hibernate.dialect.PostgreSQLDialect
mybatis:
  mapper-locations: classpath:mappers/*.xml



